---
- name: packages
  loop: "{{ packages }}"
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest

- name: service
  loop: "{{ packages }}"
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started

- name: firewall
  loop: "{{ rules }}"
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true

- name: template
  ansible.builtin.template:
    src: ./index.html.j2
    dest: /var/www/html/index.html
