---
- name: packages
  loop: "{{ packages }}"
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present

- name: service
  loop: "{{ packages }}"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true

- name: firewall
  loop: "{{ rules }}"
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true

- name: index
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
