---
- name: create user
  hosts: dev test
  become: true
  vars_files:
    - user_list.yml
    - vault.yml
  tasks:
    - name: ensure group exists
      ansible.builtin.group:
        name: devops
        state: present

    - name: create user based on job desc
      when: item.job == 'developer'
      loop: "{{ users }}"
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /bin/bash
        uid: "{{ item.uid }}"
        groups: devops
        append: true
        password: "{{ 'dev_pass' | password_hash('sha512') }}"


- name: create user
  hosts: prod
  become: true
  vars_files:
    - user_list.yml
    - vault.yml
  tasks:
    - name: ensure group exists
      ansible.builtin.group:
        name: managers
        state: present

    - name: create user based on job desc
      when: item.job == 'manager'
      loop: "{{ users }}"
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /bin/bash
        uid: "{{ item.uid }}"
        groups: managers
        append: true
        password: "{{ 'mgr_pass' | password_hash('sha512') }}"
