---
- name: create users
  hosts: all
  become: true
  vars_files:
    - vault.yml
  vars:
    users:
      - name: adam
        job: developer
        uid: 3000
        password_expire_max: 30
      - name: gabriel
        job: manager
        uid: 3001
        password_expire_max: 30
      - name: lucifer
        job: developer
        uid: 3002
        password_expire_max: 30
  tasks:
    - name: create group
      ansible.builtin.group:
        name: developer
        state: present

    - name: create users
      loop: "{{ users }}"
      when: item.job == 'developer'
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /bin/bash
        uid: "{{ item.uid }}"
        group: developer
        password_expire_max: "{{ item.password_expire_max }}"
        password: "{{ 'dev_pass' | password_hash('sha512') }}"
- name: create users
  hosts: all
  become: true
  vars_files:
    - vault.yml
  vars:
    users:
      - name: adam
        job: developer
        uid: 3000
        password_expire_max: 30
      - name: gabriel
        job: manager
        uid: 3001
        password_expire_max: 30
      - name: lucifer
        job: developer
        uid: 3002
        password_expire_max: 30
  tasks:
    - name: crate group
      ansible.builtin.group:
        name: manager
        state: present
    - name: create users
      loop: "{{ users }}"
      when: item.job == 'manager'
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /bin/bash
        uid: "{{ item.uid }}"
        group: manager
        password_expire_max: "{{ item.password_expire_max }}"
        password: "{{ 'mgr_pass' | password_hash('sha512') }}"
