---
- name: cron
  hosts: all
  become: true
  tasks:
    - name: create user celi
      ansible.builtin.user:
        name: celi

    - name: cron
      ansible.builtin.cron:
        name: cron
        job: 'logger echo "password"'
        user: celi
        minute: "*/2"
