---
- name: cron as celi
  hosts: all
  become: true
  tasks:
    - name: create user
      ansible.builtin.user:
        name: celi
        shell: /bin/bash

    - name: cron
      ansible.builtin.cron:
        name: cron as celi
        job: "'logger' echo 'Ex294'"
        minute: "*/2"
        user: celi

