---
- name: cron as araceli
  hosts: all
  become: true
  tasks:
    - name: create user
      ansible.builtin.user:
        name: araceli
        state: present
        shell: /bin/bash
    - name: cron
      ansible.builtin.cron:
        name: cron as araceli
        job: 'logger echo "EX294 in progress"'
        minute: "*/2"
        user: araceli

