---
- name: hwreport
  hosts: all
  become: true
  tasks:
    - name: download url
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/RedHatRanger/RHCE9Vagrant/main/rhce-practice-questions/golden_files/hwreport.txt
        dest: /root/hwreport.txt

    - name: configure report
      ansible.builtin.replace:
        dest: /root/hwreport.txt
        regexp: "{{ item.old }}"
        replace: "{{ item.new }}"
      loop:
        - old: "inventoryhostname"
          new: "{{ ansible.hostname | default ('NONE') }}"
        - old: "memory_in_MB"
          new: "{{ ansible_memory_mb.real.size | default ('NONE') }}"
        - old: "BIOS_version"
          new: "{{ ansible_bios_version | default ('NONE') }}"
        - old: "disk_sda_size"
          new: "{{ ansible.devices.sda.size | default ('NONE') }}"
        - old: "disk_sdb_size"
          new: "{{ ansible.devices.sdb.size | default ('NONE') }}"
