---
- name: issue
  hosts: all
  become: true
  tasks:
    - name: copy a line to a file based on group
      when: inventory_hostname in groups['dev']
      ansible.builtin.copy:
        content: "DEV"
        dest: /etc/myisse

    - name: copy a line to a file based on group
      when: inventory_hostname in groups['test']
      ansible.builtin.copy:
        content: "test"
        dest: /etc/myisse
    
    - name: copy a line to a file based on group
      when: inventory_hostname in groups['prod']
      ansible.builtin.copy:
        content: "prod"
        dest: /etc/myisse
