---
- name: issue
  hosts: all
  become: true
  tasks:
    - name: copy on dev
      when: inventory_hostname in groups['dev']
      ansible.builtin.copy:
        content: "DEVVVVVS"
        dest: /etc/issue
    - name: copy on prod
      when: inventory_hostname in groups['prod']
      ansible.builtin.copy:
        content: "PSSSS"
        dest: /etc/issue
    - name: copy on test 
      when: inventory_hostname in groups['test']
      ansible.builtin.copy:
        content: "Test"
        dest: /etc/issue
