---
- name: lvm
  hosts: all
  become: true
  tasks:
    - name: block
      block:
        - name: ensure vg is defined
          when:  ansible_lvm.vgs.research is not  defined 
          ansible.builtin.debug:
            msg: "VG not defined"

        - name: create lv
          when: ansible_lvm.vgs.research is defined
          community.general.lvol:
            vg: research
            lv: data
            size: 1200M

      rescue:
        - name: ensure vg has adequate space
          when:  ansible_lvm.vgs.research is  defined 
          ansible.builtin.debug:
            msg: "VG not enough space"

        - name: create lv
          when: ansible_lvm.vgs.research is defined
          community.general.lvol:
            vg: research
            lv: data
            size: 800M  
         
      always:
        - name: always create 
          when: ansible_lvm.vgs.research is defined
          community.general.filesystem:
            dev: /dev/research/data
            fstype: ext4

