---
- name: lvm
  hosts: all
  become: true
  tasks:
    - name: block
      block:
        - name: ensure
          when: "'research' not in ansible_devices"
          ansible.builtin.debug:
            msg: "DISK NOT PRESENT"

        - name: create
          when:  "'research' in ansible_devices"
          community.general.lvol:
            vg: research
            lv: data
            size: 1200M

      rescue:
        - name: create lvol
          when: "'research' in ansible_devices"
          ansible.builtin.debug:
            msg: "DISK NOT LARGE ENOUGH"

        - name: create
          when:  "'research' in ansible_devices"
          community.general.lvol:
            vg: research
            lv: data
            size: 800M

      always: 
        - name: create fs
          when: "'data' in ansible_devices"
          community.general.filesystem:
            device: /dev/research/data
            fstype: ext4

