---
- name: packages
  hosts: all
  become: true
  tasks:
    - name: packages on dev and test
      loop:
        - php
        - mariadb
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest

    - name: install rpm dev tools on dev
      when: inventory_hostname in groups['dev']
      ansible.builtin.dnf:
        name: '@RPM Development Tools'
        state: latest

    - name: update all on dev
      when: inventory_hostname in groups['dev']
      ansible.builtin.dnf:
        name: "*"
        state: latest


