
---
- name: packages
  hosts: dev test prod
  become: true
  tasks:
    - name: install php and mariadb
      ansible.builtin.dnf:
        name:
          - php
          - mariadb
        state: present

- name: rpm tools
  hosts: dev
  become: true
  tasks:
    - name: dev tools
      ansible.builtin.dnf:
        name: "@RPM Development Tools"
        state: present

    - name: update
      ansible.builtin.dnf:
        name: "*"
        state: latest

