---
- name: part
  hosts: all
  become: true
  tasks:
    - name: block
      block:
        - name: ensure part is defined
          when: ansbile_devices.sdb is not defined
          ansible.builtin.debug:
            msg: "PART NOT DEFINED"

        - name: create part 1000
          when: ansible_devices.sdb is defined
          community.general.parted:
            device: /dev/sdb
            number: 1
            fs_type: ext4
            part_end: 1000MiB

      rescue:
        - name: ensure part is defined
          when: ansbile_devices.sdb is not defined
          ansible.builtin.debug:
            msg: "PART NOT large enough"

        - name: create part 800
          when: ansible_devices.sdb is defined
          community.general.parted:
            device: /dev/sdb
            number: 1
            fs_type: ext4
            part_end: 800MiB

      always:
        - name: create fs
          when: ansible_devices.sdb1 is defined
          community.general.filesystem:
            fstype: ext4
            dev: /dev/sdb1
