---
- name: part
  hosts: all
  become: true
  tasks:
    - name: block
      block:
        - name: ensure partition is defined
          when: ansible_devices.sdb is not defined
          ansible.builtin.debug:
            msg: "disk no defined"

        - name: create 1200 m part
          when: ansible_devices.sdb is defined
          community.general.parted:
            device: /dev/sdb
            number: 1
            fs_type: ext4
            part_end: 1200MiB

      rescue:
        - name:  ensure partition has enough space
          when: ansible_devices.sdb is not defined
          ansible.builtin.debug:
            msg: "disk not LARGE enough"

        - name: ansible_devices.sdb is defined
          community.general.parted:
            device: /dev/sdb
            number: 1
            fs_type: ext4
            part_end: 800MiB

      always:
        - name: create fs
          when: ansible_devices.sdb is defined
          community.general.filesystem:
            dev: /dev/sdb1
            fstype: ext4

        - name: mount if on prod
          when: inventory_hostname in groups['prod']
          ansible.posix.mount:
            path: /srv
            src: /dev/sdb1
            fstype: ext4
            state: mounted

