---
- name: repos
  hosts: test
  become: true
  tasks:
    - name: repo
      ansible.builtin.yum_repository:
        name: repo
        baseurl: file:///mnt/BaseOS/
        description: Base OS Repo
        gpgcheck: false
        enabled: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-9
    - name: AppStream repo
      ansible.builtin.yum_repository:
        name: AppStream
        baseurl: file:///mnt/AppStream/
        description: AppStream Repo
        gpgcheck: false
        enabled: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-9
