---
- name: webcontent
  hosts: all
  become: true
  tasks:
    - name: ensure group exists
      ansible.builtin.group:
        name: devops2
        state: present

    - name: create directory
      ansible.builtin.file:
        path: /devops2
        state: directory
        owner: root
        group: devops2
        mode: '2755'
        setype: httpd_sys_content_t

    - name: index 
      ansible.builtin.copy:
        content: "OH SHIT"
        dest: /devops2/index.html
        owner: root
        group: root
        mode: '0644'
        setype: httpd_sys_content_t

    - name: sym
      ansible.builtin.file:
        src: /devops2
        dest: /var/www/html/devops
        state: link
        force: yes
