---
- name: web
  hosts: test
  become: true
  tasks:
    - name: create group
      ansible.builtin.group:
        name: webdev
        state: present

    - name: create dir
      ansible.builtin.file:
        path: /webdev
        state: directory
        owner: root
        group: webdev
        mode: '2755'
        setype: httpd_sys_content_t

    - name: index
      ansible.builtin.copy:
        content: "DEVS"
        dest: /webdev/index.html
        owner: root
        group: root
        mode: '0644'
        setype: httpd_sys_content_t

    - name: link
      ansible.builtin.file:
        src: /webdev
        dest: /var/www/html/webdev
        state: link
        force: true
