---
- name: webdev
  hosts: all
  become: true
  tasks:
    - name: ensure groups exists
      ansible.builtin.group:
        name: webdev
        state: present

    - name: create dir
      ansible.builtin.file:
        name: webdev
        path: /webdev
        group: webdev
        mode: 2755
        state: directory
        setype: httpd_sys_content_t

    - name: create var
      ansible.builtin.file:
        path: /var/www/html/webdev
        state: directory

    - name: sym
      ansible.builtin.file:
        src: /var/www/html/webdev
        dest: /webdev
        state: link
